### PR TITLE
initial openocd support

### PR DESCRIPTION
**Pull request by Hector93**
implementation of functions to use openocd instead of st-util, this is useful when you are working with RTOS projects, with this pull request you can debug those projects, but further documentation is required in the project of the user, I'm working on that part of the documentation.

### CODE REVIEW

**Comment by SL-RU** [comment]
Thank you! I'm using OpenOCD for some time too and have been planning to implement the same functionality. Also thank you for the documentation. 
I think to define "board.cfg" as defcustom and rename by default it to "openocd.cfg" to distinguish it from other .cfg files

**Comment by SL-RU** [comment]
I've made the commit with few fixes and  added defcustom for the .cfg

**Comment by SL-RU** [comment]
Also I'm planning to publish it to the melpa when it will be documented enough.

**Comment by Hector93** [comment]
hi, it will be nice to make this package part of melpa, i've been using ir for a couple of years now, but the modifications were only for me, but i think its better to share them, if you need help for making this package part of melpa, i can help you with that.

**Pull request merged**
